{{- if and (not .Values.certs.caName) (not .Values.certs.tlsName) }}
{{ $ca := genCA "dex-ca" 1000 }}
{{ $svcName := include "dex.fullname" . }}
{{ $cn := printf "%s.%s" $svcName .Release.Namespace}}
{{ $altName := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{ $server := genSignedCert $cn (list "127.0.0.1") (list $altName) 1000 $ca }}
{{ $client := genSignedCert "" nil nil 1000 $ca }}

apiVersion: v1
kind: List
metadata:
items:

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: {{ printf "%s-ca" ( include "dex.fullname" . ) | quote }}
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  data:
    dex-ca.pem: {{ b64enc $ca.Cert }}

- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ printf "%s-tls" ( include "dex.fullname" . ) | quote }}
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  data:
    tls.crt: {{ b64enc $server.Cert }}
    tls.key: {{ b64enc $server.Key }}
    cli.key: {{ b64enc $client.Key }}
    cli.crt: {{ b64enc $client.Cert }}

- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ printf "%s-ca" ( include "dex.fullname" . ) | quote }}
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  data:
    tls.crt: {{ b64enc $ca.Cert }}
    tls.key: {{ b64enc $ca.Key }}

{{- end }}
